package com.commanderpepper.advancecounter.database.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * @param id ID of the counter, auto generated by Room
 * @param name name of the counter
 * @param value value of the counter
 * @param step value that the counter changes when the user increment / decrements
 * @param threshold next value that will trigger an event informing other counters
 * @param parentId parent ID of the counter, if null then the counter is a parent
 */
@Entity
data class Counter (
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,
    @ColumnInfo(defaultValue = "0")
    val value: Long = 0,
    val step: Long = 1,
    val threshold: Long = 1,
    val parentId: Long? = null
)